name: KitPvP
author: Cervinakuy
main: com.planetgallium.kitpvp.Game
version: ${project.version}
description: The ultimate all-in-one KitPvP plugin.
website: https://www.spigotmc.org/resources/27107/
softdepend: [PlaceholderAPI, WorldGuard]
api-version: 1.13

commands:
   kitpvp:
     description: Main command.
     aliases: [kp, kit-pvp]
   ckit:
     description: Select a kit.
   cspawn:
     description: Teleports you to the spawn.
   ckits:
     description: View all available kits.
   cstats:
     description: View your stats.
# Basic player features are granted to everyone by default
permissions:
   kp.command.kits:
     default: true
   kp.command.menu:
     default: true
   kp.command.preview:
     default: true
   kp.command.stats:
     default: true
   kp.command.spawn:
     default: true
   kp.command.clear:
     default: true
   kp.soupreturn:
     default: true
   kp.arrowreturn:
     default: true
